# Site settings
title: MayuzhongBlog
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 黑豆
user_description: I think very good
user_title: A chasing the dream of the white
email: 1204451527@qq.com
twitter_username: lorem_ipsum
github_username:  Mayuzhong
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
